---
title: "Inter_Analyis"
date: "2025-05-29"
output: html_document
---

```{r}
### LOAD IN PACKAGES

library(tidyverse)
library(cowplot)
library(coda)
library(modelbased)
library(colorspace)
library(brms)
library(ggpubr)
library(bayesplot)
library(rlang)
library(stringr)
```

```{r}
### LOAD IN DATA

#FORAGE W/OUT ABUNDANCES FROM MASSES
forage_og <- read.csv("~/FoRAGE_Inter_Fits_Bolker_Abund_CI.csv")

#FORAGE WITH ABUNDANCES FROM MASSES
forage_fits_abun <- read_csv("~/forage_modified_bolker_Abund_CI.csv")

#REMOVE PROBLEM DATASETS
forage_fits_abun <- forage_fits_abun %>%
                 #filter(Dim != 2.5) %>%
                subset(!Inter_ID %in% c(15)) %>%
                filter(fitted_w > 0)

#ADD STUDIES THAT DID NOT HAVE MASS

forage_fits_abun <- bind_rows(
  forage_fits_abun,
  forage_og %>% 
    filter(Inter_ID %in% c(14, 25)))

```

```{r}
#Create Column for Pred mass/Prey mass

forage_fits_abun$pred_prey_mass_ratio <- forage_fits_abun$Pred_mass/forage_fits_abun$Prey_mass

#create column for w/ah

forage_fits_abun$w_ah_ratio <- forage_fits_abun$fitted_w/(forage_fits_abun$fitted_h*forage_fits_abun$scaled_a)

```

```{r}
### Add new columns with variables in log scale for linear regressions

forage_fits_abun <- forage_fits_abun %>%
  mutate(
    log_scaled_a = log(scaled_a),
    log_fitted_h = log(fitted_h),
    log_fitted_w = log(fitted_w),
    log_prey_mass = log(Prey_mass),
    log_pred_mass = log(Pred_mass),
    log_pred_prey_mass_ratio = log(pred_prey_mass_ratio),
    log_C_R_5 = log(C_R_5),
    log_C_R_25 = log(C_R_25),
    log_C_R_50 = log(C_R_50),
    log_C_R_75 = log(C_R_75),
    log_C_R_95 = log(C_R_95),
    log_wC_ahR_5 = log(wC_ahR_5),
    log_wC_ahR_25 = log(wC_ahR_25),
    log_wC_ahR_50 = log(wC_ahR_50),
    log_wC_ahR_75 = log(wC_ahR_75),
    log_wC_ahR_95 = log(wC_ahR_95),
    log_w_ah_ratio = log(w_ah_ratio)
  )
```

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////REGRESSIONS //////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////// CHANGE IN W WITH CHANGE IN FR PARS //////////////////////////////////////////////////


```{r}
### W VS A

fit_a_w_2D <- brm(log_fitted_w ~ log_scaled_a, 
                   data = filter(forage_fits_abun, Dim %in% c(2)), 
                   chains = 4,
                   iter = 10000,
                   warmup = floor(10000/2))

fit_a_w_3D <- brm(log_fitted_w ~ log_scaled_a, 
                   data = filter(forage_fits_abun, Dim %in% c(3)), 
                   chains = 4,
                   iter = 10000,
                   warmup = floor(10000/2))
```

```{r}
### W VS H

fit_h_w_2D <- brm(log_fitted_w ~ log_fitted_h, 
                   data = filter(forage_fits_abun, Dim %in% c(2)), 
                   chains = 4,
                   iter = 10000,
                   warmup = floor(10000/2))

fit_h_w_3D <- brm(log_fitted_w ~ log_fitted_h, 
                   data = filter(forage_fits_abun, Dim %in% c(3)), 
                   chains = 4,
                   iter = 10000,
                   warmup = floor(10000/2))
```

//////////////////////////////////////////////// CHANGE IN W WITH CHANGE IN MASS //////////////////////////////////////////////////

```{r}
### W VS PREY MASS

fit_w_prey_mass_2D <- brm(log_fitted_w ~ log_prey_mass, 
                   data = filter(forage_fits_abun, Dim %in% c(2), !is.na(log_prey_mass)), 
                   chains = 4,
                   iter = 10000,
                   warmup = floor(10000/2))

fit_w_prey_mass_3D <- brm(log_fitted_w ~ log_prey_mass, 
                   data = filter(forage_fits_abun, Dim %in% c(3), !is.na(log_prey_mass)), 
                   chains = 4,
                   iter = 10000,
                   warmup = floor(10000/2))
```

```{r}
### W VS PRED MASS

fit_w_pred_mass_2D <- brm(log_fitted_w ~ log_pred_mass, 
                   data = filter(forage_fits_abun, Dim %in% c(2), !is.na(log_pred_mass)), 
                   chains = 4,
                   iter = 10000,
                   warmup = floor(10000/2))

fit_w_pred_mass_3D <- brm(log_fitted_w ~ log_pred_mass, 
                   data = filter(forage_fits_abun, Dim %in% c(3), !is.na(log_pred_mass)), 
                   chains = 4,
                   iter = 10000,
                   warmup = floor(10000/2))

```

```{r}
save.image(file = 'Inter_Regression_fits.RData')
```
